/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as toolsLayoutRouteImport } from './routes/_toolsLayout/route'
import { Route as toolsLayoutConvertersNumberBaseImport } from './routes/_toolsLayout/converters/number-base'
import { Route as toolsLayoutConvertersJsonYamlImport } from './routes/_toolsLayout/converters/json-yaml'
import { Route as toolsLayoutConvertersJsonArrayToTableImport } from './routes/_toolsLayout/converters/json-array-to-table'
import { Route as toolsLayoutConvertersDateImport } from './routes/_toolsLayout/converters/date'
import { Route as toolsLayoutConvertersCronParserImport } from './routes/_toolsLayout/converters/cron-parser'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const toolsLayoutRouteRoute = toolsLayoutRouteImport.update({
  id: '/_toolsLayout/_route',
  getParentRoute: () => rootRoute,
} as any)

const toolsLayoutConvertersNumberBaseRoute =
  toolsLayoutConvertersNumberBaseImport.update({
    id: '/converters/number-base',
    path: '/converters/number-base',
    getParentRoute: () => toolsLayoutRouteRoute,
  } as any)

const toolsLayoutConvertersJsonYamlRoute =
  toolsLayoutConvertersJsonYamlImport.update({
    id: '/converters/json-yaml',
    path: '/converters/json-yaml',
    getParentRoute: () => toolsLayoutRouteRoute,
  } as any)

const toolsLayoutConvertersJsonArrayToTableRoute =
  toolsLayoutConvertersJsonArrayToTableImport.update({
    id: '/converters/json-array-to-table',
    path: '/converters/json-array-to-table',
    getParentRoute: () => toolsLayoutRouteRoute,
  } as any)

const toolsLayoutConvertersDateRoute = toolsLayoutConvertersDateImport.update({
  id: '/converters/date',
  path: '/converters/date',
  getParentRoute: () => toolsLayoutRouteRoute,
} as any)

const toolsLayoutConvertersCronParserRoute =
  toolsLayoutConvertersCronParserImport.update({
    id: '/converters/cron-parser',
    path: '/converters/cron-parser',
    getParentRoute: () => toolsLayoutRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_toolsLayout/_route': {
      id: '/_toolsLayout/_route'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof toolsLayoutRouteImport
      parentRoute: typeof rootRoute
    }
    '/_toolsLayout/_route/converters/cron-parser': {
      id: '/_toolsLayout/_route/converters/cron-parser'
      path: '/converters/cron-parser'
      fullPath: '/converters/cron-parser'
      preLoaderRoute: typeof toolsLayoutConvertersCronParserImport
      parentRoute: typeof toolsLayoutRouteImport
    }
    '/_toolsLayout/_route/converters/date': {
      id: '/_toolsLayout/_route/converters/date'
      path: '/converters/date'
      fullPath: '/converters/date'
      preLoaderRoute: typeof toolsLayoutConvertersDateImport
      parentRoute: typeof toolsLayoutRouteImport
    }
    '/_toolsLayout/_route/converters/json-array-to-table': {
      id: '/_toolsLayout/_route/converters/json-array-to-table'
      path: '/converters/json-array-to-table'
      fullPath: '/converters/json-array-to-table'
      preLoaderRoute: typeof toolsLayoutConvertersJsonArrayToTableImport
      parentRoute: typeof toolsLayoutRouteImport
    }
    '/_toolsLayout/_route/converters/json-yaml': {
      id: '/_toolsLayout/_route/converters/json-yaml'
      path: '/converters/json-yaml'
      fullPath: '/converters/json-yaml'
      preLoaderRoute: typeof toolsLayoutConvertersJsonYamlImport
      parentRoute: typeof toolsLayoutRouteImport
    }
    '/_toolsLayout/_route/converters/number-base': {
      id: '/_toolsLayout/_route/converters/number-base'
      path: '/converters/number-base'
      fullPath: '/converters/number-base'
      preLoaderRoute: typeof toolsLayoutConvertersNumberBaseImport
      parentRoute: typeof toolsLayoutRouteImport
    }
  }
}

// Create and export the route tree

interface toolsLayoutRouteRouteChildren {
  toolsLayoutConvertersCronParserRoute: typeof toolsLayoutConvertersCronParserRoute
  toolsLayoutConvertersDateRoute: typeof toolsLayoutConvertersDateRoute
  toolsLayoutConvertersJsonArrayToTableRoute: typeof toolsLayoutConvertersJsonArrayToTableRoute
  toolsLayoutConvertersJsonYamlRoute: typeof toolsLayoutConvertersJsonYamlRoute
  toolsLayoutConvertersNumberBaseRoute: typeof toolsLayoutConvertersNumberBaseRoute
}

const toolsLayoutRouteRouteChildren: toolsLayoutRouteRouteChildren = {
  toolsLayoutConvertersCronParserRoute: toolsLayoutConvertersCronParserRoute,
  toolsLayoutConvertersDateRoute: toolsLayoutConvertersDateRoute,
  toolsLayoutConvertersJsonArrayToTableRoute:
    toolsLayoutConvertersJsonArrayToTableRoute,
  toolsLayoutConvertersJsonYamlRoute: toolsLayoutConvertersJsonYamlRoute,
  toolsLayoutConvertersNumberBaseRoute: toolsLayoutConvertersNumberBaseRoute,
}

const toolsLayoutRouteRouteWithChildren =
  toolsLayoutRouteRoute._addFileChildren(toolsLayoutRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof toolsLayoutRouteRouteWithChildren
  '/converters/cron-parser': typeof toolsLayoutConvertersCronParserRoute
  '/converters/date': typeof toolsLayoutConvertersDateRoute
  '/converters/json-array-to-table': typeof toolsLayoutConvertersJsonArrayToTableRoute
  '/converters/json-yaml': typeof toolsLayoutConvertersJsonYamlRoute
  '/converters/number-base': typeof toolsLayoutConvertersNumberBaseRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof toolsLayoutRouteRouteWithChildren
  '/converters/cron-parser': typeof toolsLayoutConvertersCronParserRoute
  '/converters/date': typeof toolsLayoutConvertersDateRoute
  '/converters/json-array-to-table': typeof toolsLayoutConvertersJsonArrayToTableRoute
  '/converters/json-yaml': typeof toolsLayoutConvertersJsonYamlRoute
  '/converters/number-base': typeof toolsLayoutConvertersNumberBaseRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_toolsLayout/_route': typeof toolsLayoutRouteRouteWithChildren
  '/_toolsLayout/_route/converters/cron-parser': typeof toolsLayoutConvertersCronParserRoute
  '/_toolsLayout/_route/converters/date': typeof toolsLayoutConvertersDateRoute
  '/_toolsLayout/_route/converters/json-array-to-table': typeof toolsLayoutConvertersJsonArrayToTableRoute
  '/_toolsLayout/_route/converters/json-yaml': typeof toolsLayoutConvertersJsonYamlRoute
  '/_toolsLayout/_route/converters/number-base': typeof toolsLayoutConvertersNumberBaseRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/converters/cron-parser'
    | '/converters/date'
    | '/converters/json-array-to-table'
    | '/converters/json-yaml'
    | '/converters/number-base'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/converters/cron-parser'
    | '/converters/date'
    | '/converters/json-array-to-table'
    | '/converters/json-yaml'
    | '/converters/number-base'
  id:
    | '__root__'
    | '/'
    | '/_toolsLayout/_route'
    | '/_toolsLayout/_route/converters/cron-parser'
    | '/_toolsLayout/_route/converters/date'
    | '/_toolsLayout/_route/converters/json-array-to-table'
    | '/_toolsLayout/_route/converters/json-yaml'
    | '/_toolsLayout/_route/converters/number-base'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  toolsLayoutRouteRoute: typeof toolsLayoutRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  toolsLayoutRouteRoute: toolsLayoutRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_toolsLayout/_route"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_toolsLayout/_route": {
      "filePath": "_toolsLayout/route.tsx",
      "children": [
        "/_toolsLayout/_route/converters/cron-parser",
        "/_toolsLayout/_route/converters/date",
        "/_toolsLayout/_route/converters/json-array-to-table",
        "/_toolsLayout/_route/converters/json-yaml",
        "/_toolsLayout/_route/converters/number-base"
      ]
    },
    "/_toolsLayout/_route/converters/cron-parser": {
      "filePath": "_toolsLayout/converters/cron-parser.tsx",
      "parent": "/_toolsLayout/_route"
    },
    "/_toolsLayout/_route/converters/date": {
      "filePath": "_toolsLayout/converters/date.tsx",
      "parent": "/_toolsLayout/_route"
    },
    "/_toolsLayout/_route/converters/json-array-to-table": {
      "filePath": "_toolsLayout/converters/json-array-to-table.tsx",
      "parent": "/_toolsLayout/_route"
    },
    "/_toolsLayout/_route/converters/json-yaml": {
      "filePath": "_toolsLayout/converters/json-yaml.tsx",
      "parent": "/_toolsLayout/_route"
    },
    "/_toolsLayout/_route/converters/number-base": {
      "filePath": "_toolsLayout/converters/number-base.tsx",
      "parent": "/_toolsLayout/_route"
    }
  }
}
ROUTE_MANIFEST_END */
